### ISSUE TITLE
Abstract Location, beyond socket and gRPC to rsocket and reactive streams

### ISSUE THREAD

**Issue by SemanticBeeng** [BryanCutler/SparkArrowFlight#2]
Would like to use `ArrowFlight` with `rsocket` and `reactive streams`. 

The code repo in this great but `Location` is bound to use sockets and `gRPC`.
Is this strictly necessary or could be be further extended in this sense?

https://medium.com/netifi/differences-between-grpc-and-rsocket-e736c954e60
> RSocket is an OSI layer 5/6 that models Reactive Streams semantics over a network

Specifically need to stream from `Cloudflow` over `rsocket` as in these articles
 * https://www.lightbend.com/blog/implementing-rsocket-ingress-in-cloudflow-part-1-getting-started
 * https://www.lightbend.com/blog/implementing-rsocket-ingress-in-cloudflow-part-2-advanced-features
 * https://www.lightbend.com/blog/implementing-rsocket-ingress-in-cloudflow-part-3-pluggable-transport

@BryanCutler @wesm kindly advise

**Comment by BryanCutler** [comment]
Hi @SemanticBeeng , thanks for checking this out. Arrow Flight is designed to be able to other frameworks than gRPC, but I think that is all the current implementations have. It would be great for you to experiment with another framework and report back to the Arrow mailing list.

As for Spark + Flight, I think the better approach is to use Flight in as a Spark V2 datasource. I'd like to have that available someday, for now here is a Spark datasource for loading from Flight https://github.com/rymurr/flight-spark-source
